version: '3'

services:
  webnote:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - FLASK_APP=app.py
      - DATABASE_URI=sqlite:////app/data/webnote.db
      - SECRET_KEY=change-this-in-production
      - HELPEMAIL=youremail@example.com
      - DEBUG=0
      - NUM_DATES=10
      - TIMEZONE=US/Eastern
    restart: unless-stopped